In [ ]:
import tweepy

In [ ]:
import jsonpickle

In [ ]:
import pandas as pd
import tweepy
import jsonpickle
import json
import re
import matplotlib as plt
import numpy as np

In [ ]:
CONSUMER_KEY    = 'sz6x0nvL0ls9wacR64MZu23z4'
CONSUMER_SECRET = 'ofeGnzduikcHX6iaQMqBCIJ666m6nXAQACIAXMJaFhmC6rjRmT'
ACCESS_TOKEN  = '854004678127910913-PUPfQYxIjpBWjXOgE25kys8kmDJdY0G'
ACCESS_SECRET = 'BC2TxbhKXkdkZ91DXofF7GX8p2JNfbpHqhshW1bwQkgxN'
def connect_to_twitter_OAuth():
    auth = tweepy.OAuthHandler(CONSUMER_KEY, CONSUMER_SECRET)
    auth.set_access_token(ACCESS_TOKEN, ACCESS_SECRET)
    
    api = tweepy.API(auth)
    return api
api = connect_to_twitter_OAuth()

In [ ]:
def get_save_tweets(filepath, api, query, max_tweets=50000, lang='en'):

    tweetCount = 0

    #Open file and save tweets
    with open(filepath, 'w') as f:

        # Send the query
        for tweet in tweepy.Cursor(api.search,q=query,lang=lang).items(max_tweets):         

            #Convert to JSON format
            f.write(jsonpickle.encode(tweet._json, unpicklable=False) + '\n')
            tweetCount += 1

        #Display how many tweets we have collected
        print("Downloaded {0} tweets".format(tweetCount))

In [ ]:
query = '#realmadrid OR #barcelona OR #atletico OR #sevilla OR #valencia'

# Get those tweets
get_save_tweets('tweets.json', api, query)

In [ ]:
def tweets_to_df(path):
    
    tweets = list(open('tweets.json', 'rt'))
    
    text = []
    weekday = []
    month = []
    day = []
    hour = []
    hashtag = []
    url = []
    favorite = []
    reply = []
    retweet = []
    follower = []
    following = []
    user = []
    location = []
    screen_name = []

    for t in tweets:
        t = jsonpickle.decode(t)
        
        # Text
        text.append(t['text'])
        
        # Decompose date
        date = t['created_at']
        weekday.append(date.split(' ')[0])
        month.append(date.split(' ')[1])
        day.append(date.split(' ')[2])
        
        time = date.split(' ')[3].split(':')
        hour.append(time[0]) 
        
        # Has hashtag
        if len(t['entities']['hashtags']) == 0:
            hashtag.append(0)
        else:
            hashtag.append(1)
            
        # Has url
        if len(t['entities']['urls']) == 0:
            url.append(0)
        else:
            url.append(1)
            
        # Number of favs
        favorite.append(t['favorite_count'])
        
        # Is reply?
        if t['in_reply_to_status_id'] == None:
            reply.append(0)
        else:
            reply.append(1)       
        
        # Retweets count
        retweet.append(t['retweet_count'])
        
        # Followers number
        follower.append(t['user']['followers_count'])
        
        # Following number
        following.append(t['user']['friends_count'])
        
        # Add user
        user.append(t['user']['name'])
        
        # Add location
        location.append(t['user']['location'])

        # Add screen name
        screen_name.append(t['user']['screen_name'])
        
    d = {'text': text,
         'weekday': weekday,
         'month' : month,
         'day': day,
         'hour' : hour,
         'has_hashtag': hashtag,
         'has_url': url,
         'fav_count': favorite,
         'is_reply': reply,
         'retweet_count': retweet,
         'followers': follower,
         'following' : following,
         'user': user,
         'location': location,
         'screen_name' : screen_name
        }
    
    return pd.DataFrame(data = d)
        
tweets_df = tweets_to_df('tweets.json')

In [ ]:
def tweets_to_df(path):
    
    tweets = list(open('tweets1.json', 'rt'))
    
    text = []
    weekday = []
    month = []
    day = []
    hour = []
    hashtag = []
    url = []
    favorite = []
    reply = []
    retweet = []
    follower = []
    following = []
    user = []
    location = []
    screen_name = []

    for t in tweets:
        t = jsonpickle.decode(t)
        
        # Text
        text.append(t['text'])
        
        # Decompose date
        date = t['created_at']
        weekday.append(date.split(' ')[0])
        month.append(date.split(' ')[1])
        day.append(date.split(' ')[2])
        
        time = date.split(' ')[3].split(':')
        hour.append(time[0]) 
        
        # Has hashtag
        if len(t['entities']['hashtags']) == 0:
            hashtag.append(0)
        else:
            hashtag.append(1)
            
        # Has url
        if len(t['entities']['urls']) == 0:
            url.append(0)
        else:
            url.append(1)
            
        # Number of favs
        favorite.append(t['favorite_count'])
        
        # Is reply?
        if t['in_reply_to_status_id'] == None:
            reply.append(0)
        else:
            reply.append(1)       
        
        # Retweets count
        retweet.append(t['retweet_count'])
        
        # Followers number
        follower.append(t['user']['followers_count'])
        
        # Following number
        following.append(t['user']['friends_count'])
        
        # Add user
        user.append(t['user']['name'])
        
        # Add location
        location.append(t['user']['location'])

        # Add screen name
        screen_name.append(t['user']['screen_name'])
        
    d = {'text': text,
         'weekday': weekday,
         'month' : month,
         'day': day,
         'hour' : hour,
         'has_hashtag': hashtag,
         'has_url': url,
         'fav_count': favorite,
         'is_reply': reply,
         'retweet_count': retweet,
         'followers': follower,
         'following' : following,
         'user': user,
         'location': location,
         'screen_name' : screen_name
        }
    
    return pd.DataFrame(data = d)
        
tweets_df2 = tweets_to_df('tweets1.json')

In [ ]:
def tweets_to_df(path):
    
    tweets = list(open('tweets2.json', 'rt'))
    
    text = []
    weekday = []
    month = []
    day = []
    hour = []
    hashtag = []
    url = []
    favorite = []
    reply = []
    retweet = []
    follower = []
    following = []
    user = []
    location = []
    screen_name = []

    for t in tweets:
        t = jsonpickle.decode(t)
        
        # Text
        text.append(t['text'])
        
        # Decompose date
        date = t['created_at']
        weekday.append(date.split(' ')[0])
        month.append(date.split(' ')[1])
        day.append(date.split(' ')[2])
        
        time = date.split(' ')[3].split(':')
        hour.append(time[0]) 
        
        # Has hashtag
        if len(t['entities']['hashtags']) == 0:
            hashtag.append(0)
        else:
            hashtag.append(1)
            
        # Has url
        if len(t['entities']['urls']) == 0:
            url.append(0)
        else:
            url.append(1)
            
        # Number of favs
        favorite.append(t['favorite_count'])
        
        # Is reply?
        if t['in_reply_to_status_id'] == None:
            reply.append(0)
        else:
            reply.append(1)       
        
        # Retweets count
        retweet.append(t['retweet_count'])
        
        # Followers number
        follower.append(t['user']['followers_count'])
        
        # Following number
        following.append(t['user']['friends_count'])
        
        # Add user
        user.append(t['user']['name'])
        
        # Add location
        location.append(t['user']['location'])

        # Add screen name
        screen_name.append(t['user']['screen_name'])
        
    d = {'text': text,
         'weekday': weekday,
         'month' : month,
         'day': day,
         'hour' : hour,
         'has_hashtag': hashtag,
         'has_url': url,
         'fav_count': favorite,
         'is_reply': reply,
         'retweet_count': retweet,
         'followers': follower,
         'following' : following,
         'user': user,
         'location': location,
         'screen_name' : screen_name
        }
    
    return pd.DataFrame(data = d)
        
tweets_df3 = tweets_to_df('tweets2.json')

In [ ]:
len(tweets_df2)
len(tweets_df3)

In [ ]:
tweets_df3.head(2)

In [ ]:
tweets_df2.head()

In [ ]:
df = pd.concat([tweets_df2, tweets_df3])

In [ ]:
len(df)

In [ ]:
df['lower case'] = df['text'].str.lower() #coverting tweets to lower case

In [492]:
df['E'] = df['lower case'].map(lambda x: re.sub(r'\W+', ' ', x)) #removing all the special characters, links, URLs, blank spaces

In [421]:
df['E']

0       good morning barcelona good advice for barça f...
1       rt yusufchambers mosalah gets injured ramadhan...
2        finalscoresbet fsb winfornow this is the most...
3       rt lfcphoto no problem lfc livbar championslea...
4       rt marcabimbo we choose to believe in us mazai...
5       rt lfcphoto no problem lfc livbar championslea...
6       rt oluwafemig 60secondswithfemi korrect pidgin...
7        barcelona i am inevitable liverpool i am live...
8       which lfc comeback was better championsleague ...
9       real madrid prepare world record bid for kylia...
10      rt nialloloughlin unbelievable match maybe the...
11      who saw last night coming wooooah let s hear y...
12       dublin joins barcelona belgrade buenosaires d...
13      rt ivanvaldezpy not today liverpool barcelona ...
14      rt naira4dollar never give up on what you real...
15      rt waltermurimi92 messi to dembele in the lock...
16      rt srijandeep phil coutinho lied faked an inju...
17      rt mickyjayoffici1 who did this messi barcelon...
18      unbelievable moment soccer football futbol spo...
19      bzingers__ dear barcelona fc fans this is for ...
20      bcn highlights is the ideal to cover the very ...
21      rt superyacht_tv 82m megayacht secret built by...
22      wednesday s startup and tech events coming up ...
23      rt aby_yaarr a quick one choose your goat retw...
24      rt jimmyliddel luis suarez is a disgrace i nev...
25      rt klassikal_ retweet if you still believe he ...
26      rt dpulseofficial1 former england captain alan...
27      rt klassikal_ caption this livbar livbar messi...
28      rt naira4dollar never give up on what you real...
29      former england captain alan shearer was at anf...
                              ...
2038    rt quitepeter trent alexander arnold corner wi...
2039    when you deliberately injure opponents player ...
2040    rt lfcphoto you ll never walk alone lfc livbar...
2041    actually barcelona didn t know the technique t...
2042    rt lfcphoto off to madrid lfc livbar champions...
2043    rt 9gag walk on with hope in your heart liverp...
2044    rt amitranjan one of the sneakiest goals you d...
2045    rt energevo barcelona is the first team in cha...
2046    rt jhasanjay to all my fellow liverpool lfc fa...
2047    rt 9gag walk on with hope in your heart liverp...
2048                  liverpool beat barcelona 4 0 livbar
2049    rt ifeenma may you defend your enemies like li...
2050    rt chakrapanivarad the celebrations will go on...
2051    rt mdwlivefeed breaking liverpool hammer barce...
2052    the presence of messi is not a win guaranteed ...
2053     valverde contract extension termination will ...
2054    rt suzy_qb_ thank you very much liverpool high...
2055    rt energevo barcelona is the first team in cha...
2056    rt aby_yaarr a quick one choose your goat retw...
2057    morning sky barcelona catalunya spain https t ...
2058    an example of poetic justice suarez that dirty...
2059    rt lfcphoto you ll never walk alone lfc livbar...
2060    you ll never walk alone incredible footage htt...
2061    rt bramdaanen magical night at anfield boom li...
2062    rt 9gag walk on with hope in your heart liverp...
2063    a nightmare where are you barca fans now livba...
2064    rt aby_yaarr a quick one choose your goat retw...
2065    rt me_psycho4 no difference barcelona barca li...
2066    rt powndland a quick videro message to liverpo...
2067    rt onecak liga champions liverpool vs barcelon...
Name: E, Length: 4059, dtype: object

In [ ]:
df.head(2)

In [ ]:
del df['lowercase3']

In [ ]:
df.head(2)

In [314]:
df_rm = df[df['E'].str.contains("realmadrid") | df['E'].str.contains("real madrid") |df['E'].str.contains("rma")] #tweets containing real madrid
df_barca = df[df['E'].str.contains("barcelona") | df['E'].str.contains("barca") |df['E'].str.contains("fcb")] #tweets contaiining barcelona
df_atm = df[df['E'].str.contains("atletico") | df['E'].str.contains("atm")] #tweets contaiining atletico
df_sev = df[df['E'].str.contains("sevilla") | df['E'].str.contains("sev")] #tweets contaiining sevilla
df_val = df[df['E'].str.contains("valencia") | df['E'].str.contains("val")] #tweets contaiining valencia

In [313]:
len(df_rm) # occurrence of real madrid tweets

132

In [315]:
len(df_barca) #occurrence of barcelona tweets

3038

In [305]:
len(df_atm) #occurrence of atletico madrid tweets

33

In [307]:
len(df_sev)  #occurrence of sevilla tweets

29

In [309]:
len(df_val) #occurrence of valencia tweets

216

In [ ]:
from textblob import TextBlob

In [316]:
import re
import numpy as np

In [317]:
def clean_tweet(tweet):
    '''
    Utility function to clean the text in a Tweet by removing 
    links and special characters using regex re.
    '''
    return ' '.join(re.sub("(@[A-Za-z0-9]+)|([^0-9A-Za-z \t])|(\w+:\/\/\S+)", " ", tweet).split())

def analize_sentiment(tweet):
    '''
    Utility TextBlob to classify the polarity of a Tweet
    using TextBlob.
    '''
    analysis = TextBlob(clean_tweet(tweet))
    if analysis.sentiment.polarity > 0:
        return 1
    elif analysis.sentiment.polarity == 0:
        return 0
    else:
        return -1

In [318]:
df_rm['Score'] = np.array([ analize_sentiment(tweet) for tweet in df_rm['E'] ])
df_barca['Score'] = np.array([ analize_sentiment(tweet) for tweet in df_barca['E'] ])
df_atm['Score'] = np.array([ analize_sentiment(tweet) for tweet in df_atm['E'] ])
df_sev['Score'] = np.array([ analize_sentiment(tweet) for tweet in df_sev['E'] ])
df_val['Score'] = np.array([ analize_sentiment(tweet) for tweet in df_val['E'] ])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  after removing the cwd from sys.path.
C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """

In [417]:
display(df_rm.head(15))  # We display the DataFrame with updated score
display(df_barca.head(15))
display(df_atm.head(15))
display(df_sev.head(15))
display(df_val.head(15))

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,Score
9,Real #Madrid Prepare World-Record Bid for Kyli...,Wed,May,08,09,1,1,0,0,0,53289,43739,⚽️ Football News,Deutschland,footy90com,real #madrid prepare world-record bid for kyli...,real madrid prepare world record bid for kylia...,1
81,11nt Costa Brava &amp; Mediterranean Jewels Cr...,Wed,May,08,08,0,1,0,0,0,15,0,We Love 2 Holiday,,welove2holiday,11nt costa brava &amp; mediterranean jewels cr...,11nt costa brava amp mediterranean jewels crui...,0
96,@kingarturo23 how does it feel after donating ...,Wed,May,08,08,0,1,0,0,0,2166,1943,zubair ah,"ÜT: 13.0000242,77.5781415",ZUBAIRZZEEH,@kingarturo23 how does it feel after donating ...,kingarturo23 how does it feel after donating ...,1
134,Rumours: #Real Madrid to make massive £240m mo...,Wed,May,08,08,1,1,0,0,0,53289,43739,⚽️ Football News,Deutschland,footy90com,rumours: #real madrid to make massive £240m mo...,rumours real madrid to make massive 240m move ...,1
182,RT @CzonKim: When i see this corner i remember...,Wed,May,08,08,0,0,0,0,3,528,1349,Its_tolani blue,"Toronto, Ontario",tolaniwizzy,rt @czonkim: when i see this corner i remember...,rt czonkim when i see this corner i remember w...,0
188,RT @I_PraveenMP: Fuck I love this game 👑😎 \n\n...,Wed,May,08,08,1,0,0,0,2,1008,1208,liverpool❤️❤️❤️❤️😭😭😭😍😍😍🔝🔝🔝,Santiago bernabeu,Moha_ibrahim304,rt @i_praveenmp: fuck i love this game 👑😎 \n\n...,rt i_praveenmp fuck i love this game now you k...,0
244,"Man City, Arsenal and Chelsea want Adrien Rabi...",Wed,May,08,08,0,1,0,0,0,3,76,#k,,hashkcity,"man city, arsenal and chelsea want adrien rabi...",man city arsenal and chelsea want adrien rabio...,1
245,"RT @bigjurgensarmy: So, after beating your mos...",Wed,May,08,08,1,0,0,0,1,1282,553,wendyknowsbest,,wendy161966,"rt @bigjurgensarmy: so, after beating your mos...",rt bigjurgensarmy so after beating your most h...,-1
285,RT @NicoSchira: #RealMadrid and Zizou #Zidane ...,Wed,May,08,08,1,0,0,0,57,345,1518,Ross,,essexlad99,rt @nicoschira: #realmadrid and zizou #zidane ...,rt nicoschira realmadrid and zizou zidane insi...,0
287,This is exactly what happen #LFCBarça #FCBarce...,Wed,May,08,08,1,0,0,0,0,112,123,Jorge Perez,,JPerez2591,this is exactly what happen #lfcbarça #fcbarce...,this is exactly what happen lfcbarça fcbarcelo...,1
303,Marca #claims Dani Ceballos’s time at Real Mad...,Wed,May,08,08,1,1,0,0,0,53289,43739,⚽️ Football News,Deutschland,footy90com,marca #claims dani ceballos’s time at real mad...,marca claims dani ceballos s time at real madr...,1
346,"Iker Casillas born in Mostoles, Madrid, Casill...",Wed,May,08,08,0,1,0,0,0,0,0,Nepral,India,nepral,"iker casillas born in mostoles, madrid, casill...",iker casillas born in mostoles madrid casillas...,1
386,#Barcelona #RealMadrid #Juventus #BayernMunich...,Wed,May,08,08,1,1,0,0,0,168,495,Avi Räikkönen AR7,India,avinashpattnaik,#barcelona #realmadrid #juventus #bayernmunich...,barcelona realmadrid juventus bayernmunich al...,-1
421,RT @GraphicSamHD: Luka #Jovic x #RealMadrid 20...,Wed,May,08,07,1,0,0,0,7,571,115,Real Madrid Guy 🇧🇩👑,Bangladesh,Madridista165,rt @graphicsamhd: luka #jovic x #realmadrid 20...,rt graphicsamhd luka jovic x realmadrid 2019 2...,1
491,#Anfield #10yearsChallenge\n 2009: #Liverpool ...,Wed,May,08,07,1,0,0,0,0,254,183,Jemeel Teejay Abdul,"Bauchi, Nigeria",jemeelteejay,#anfield #10yearschallenge\n 2009: #liverpool ...,anfield 10yearschallenge 2009 liverpool 4 0 r...,0

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,Score
0,Good morning #Barcelona...Good advice for #Bar...,Wed,May,08,09,1,1,0,0,0,1691,3473,Pedro de la Vega,Barcelona,BcnFox,good morning #barcelona...good advice for #bar...,good morning barcelona good advice for barça f...,1
3,RT @LFCphoto: No problem. #LFC #LIVBAR #Champi...,Wed,May,08,09,1,0,0,0,21,38,317,🍀OOR🍀THEKOP🍀핫티스🍀판타지🍀,태국.Thailand,ameerah_TY,rt @lfcphoto: no problem. #lfc #livbar #champi...,rt lfcphoto no problem lfc livbar championslea...,0
5,RT @LFCphoto: No problem. #LFC #LIVBAR #Champi...,Wed,May,08,09,1,0,0,0,21,390,428,hifnipahlevi,,hifnipahlevi,rt @lfcphoto: no problem. #lfc #livbar #champi...,rt lfcphoto no problem lfc livbar championslea...,0
6,RT @OluwafemiG: 60Secondswithfemi...korrect Pi...,Wed,May,08,09,0,0,0,0,1,719,802,Fairly Used Married Man,"Ijebu-Ode, Nigeria",MrAriyo,rt @oluwafemig: 60secondswithfemi...korrect pi...,rt oluwafemig 60secondswithfemi korrect pidgin...,0
7,#Barcelona “i am inevitable” ... #Liverpool “i...,Wed,May,08,09,1,0,0,0,0,28,174,Marshall Forever,"Roterdão, Holanda (Países Baix",marshall22jack,#barcelona “i am inevitable” ... #liverpool “i...,barcelona i am inevitable liverpool i am live...,0
8,Which #LFC comeback was better:\n\n#Championsl...,Wed,May,08,09,1,0,0,0,0,918,4303,Jon Hayes,"Redhill, South East",jonboy_avfc,which #lfc comeback was better:\n\n#championsl...,which lfc comeback was better championsleague ...,1
10,"RT @nialloloughlin: Unbelievable match, maybe ...",Wed,May,08,09,1,0,0,0,7,986,421,Ann🛸,Behind you!,annf32,"rt @nialloloughlin: unbelievable match, maybe ...",rt nialloloughlin unbelievable match maybe the...,1
12,"#Dublin joins #Barcelona , #Belgrade , #Buenos...",Wed,May,08,09,1,1,0,0,0,236,294,Francis M. O'Donnell,"Vienna, Dublin, & Cyberspace",fmod1,"#dublin joins #barcelona , #belgrade , #buenos...",dublin joins barcelona belgrade buenosaires d...,0
13,RT @ivanvaldezpy: Not today. \n#Liverpool #Bar...,Wed,May,08,09,1,0,0,0,2,11,77,Alexander Guerra,Italia,Alexguerra2378,rt @ivanvaldezpy: not today. \n#liverpool #bar...,rt ivanvaldezpy not today liverpool barcelona ...,0
15,RT @waltermurimi92: Messi to dembele in the lo...,Wed,May,08,09,1,0,0,0,59,41,86,B-HOVA,,tommyobaro,rt @waltermurimi92: messi to dembele in the lo...,rt waltermurimi92 messi to dembele in the lock...,0
17,RT @Mickyjayoffici1: Who did this?? 😂😂💔💔\n ...,Wed,May,08,09,1,0,0,0,8,1490,646,The Morningstar,Gotham,juniorbjawara,rt @mickyjayoffici1: who did this?? 😂😂💔💔\n ...,rt mickyjayoffici1 who did this messi barcelon...,0
19,bzingers__ - Dear Barcelona FC fans this is ...,Wed,May,08,09,1,1,0,0,0,680,674,nupefinest,Kurmin Kadanu Kaduna,nupe_finest,bzingers__ - dear barcelona fc fans this is ...,bzingers__ dear barcelona fc fans this is for ...,0
20,BCN Highlights is the ideal to cover the very ...,Wed,May,08,09,1,1,0,0,0,588,784,VIP BCN Tour Guides,"Av: Pau Casals, 38, 2º,5ª, BCN",BcnVIPtour,bcn highlights is the ideal to cover the very ...,bcn highlights is the ideal to cover the very ...,1
22,Wednesday's startup and tech events coming up ...,Wed,May,08,09,1,1,0,0,0,127,431,Startup Events List - Barcelona,"Barcelona, Spain",StartupEventBAR,wednesday's startup and tech events coming up ...,wednesday s startup and tech events coming up ...,0
23,RT @aby_yaarr: A quick one... Choose your GOAT...,Wed,May,08,09,1,0,0,0,353,141,590,Wonder_28,,Wonder92197961,rt @aby_yaarr: a quick one... choose your goat...,rt aby_yaarr a quick one choose your goat retw...,1

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,Score
221,RT @TheNationalUAE: “We know that this club is...,Wed,May,08,08,1,0,0,0,1,498,1754,Jade Wong,Abu Dhabi,Jade_Wong86,rt @thenationaluae: “we know that this club is...,rt thenationaluae we know that this club is a ...,0
315,Messi 2013 - BAYERN 7-0\nMessi 2014 - Bullied ...,Wed,May,08,08,0,1,0,0,0,868,662,Zeeshan Haider,"Lahore, Pakistan",iZeeshan_Haider,messi 2013 - bayern 7-0\nmessi 2014 - bullied ...,messi 2013 bayern 7 0 messi 2014 bullied by at...,0
381,2016 : Barcelona lost to Atletico 2-0\n2017: B...,Wed,May,08,08,0,1,0,0,0,393,632,Inayat Fazal 🇵🇰,"Faisalabad, Punjab, Pakistan",InayatFazal92,2016 : barcelona lost to atletico 2-0\n2017: b...,2016 barcelona lost to atletico 2 0 2017 barce...,0
412,RT @FOXSportsAsia: WATCH: What an atmosphere! ...,Wed,May,08,08,0,0,0,0,1,333,1426,chris_bautista,Manila,chris_bautista,rt @foxsportsasia: watch: what an atmosphere! ...,rt foxsportsasia watch what an atmosphere the ...,1
420,“We know that this club is a mix of atmosphere...,Wed,May,08,08,1,1,2,0,1,904364,143,The National,"Abu Dhabi, UAE",TheNationalUAE,“we know that this club is a mix of atmosphere...,we know that this club is a mix of atmosphere...,0
656,“There are more important things in the world....,Wed,May,08,07,0,1,1,0,0,2747,2049,Jochen Spangenberg,World,jospang,“there are more important things in the world....,there are more important things in the world ...,1
661,"Obi goes to hospital for treatment, names trus...",Wed,May,08,07,0,1,1,0,0,1767,4999,ceoafrica,Africa,ceoafrica,"obi goes to hospital for treatment, names trus...",obi goes to hospital for treatment names trust...,0
701,RT @FInfodata: 🇪🇸 Front page of #AS\n📰 2019-05...,Wed,May,08,07,1,0,0,0,1,681,2686,Luis Pedro Da Silva,Cidade De Maputo | Moçambique,DJLuisPedro,rt @finfodata: 🇪🇸 front page of #as\n📰 2019-05...,rt finfodata front page of as 2019 05 08 edico...,1
709,RT @FInfodata: 🇪🇸 Front page of #Marca\n📰 2019...,Wed,May,08,07,1,0,0,0,3,687,893,Huw David Williams,,HuwDaiWilliams,rt @finfodata: 🇪🇸 front page of #marca\n📰 2019...,rt finfodata front page of marca 2019 05 08 ed...,1
767,Feliç lloc. \nMy first day in #Barcelona was s...,Wed,May,08,07,1,1,0,0,0,280,386,Kate Biddle,"Atlanta, GA",katebiddle08,feliç lloc. \nmy first day in #barcelona was s...,feliç lloc my first day in barcelona was spent...,1
774,RT @FInfodata: 🇪🇸 Front page of #Marca\n📰 2019...,Wed,May,08,07,1,0,0,0,3,1864,99,Billy Campbell,Liverpool,BillyCampbell_1,rt @finfodata: 🇪🇸 front page of #marca\n📰 2019...,rt finfodata front page of marca 2019 05 08 ed...,1
1058,WATCH: What an atmosphere! 🔥🔥🔥\n\nThe Anfield ...,Wed,May,08,06,0,1,1,0,1,51286,293,FOX Sports Asia,Asia,FOXSportsAsia,watch: what an atmosphere! 🔥🔥🔥\n\nthe anfield ...,watch what an atmosphere the anfield faithful ...,1
1268,🇪🇸 Front page of #Sport\n📰 2019-05-08\n\n #edi...,Wed,May,08,05,1,0,1,0,0,6011,5078,Football⚽️InfoData,"Rome, Lazio",FInfodata,🇪🇸 front page of #sport\n📰 2019-05-08\n\n #edi...,front page of sport 2019 05 08 edicola primap...,1
1270,🇪🇸 Front page of #MundoDeportivo\n📰 2019-05-08...,Wed,May,08,05,1,0,0,0,0,6011,5078,Football⚽️InfoData,"Rome, Lazio",FInfodata,🇪🇸 front page of #mundodeportivo\n📰 2019-05-08...,front page of mundodeportivo 2019 05 08 edico...,1
1271,🇪🇸 Front page of #Marca\n📰 2019-05-08\n\n #edi...,Wed,May,08,05,1,0,1,0,3,6011,5078,Football⚽️InfoData,"Rome, Lazio",FInfodata,🇪🇸 front page of #marca\n📰 2019-05-08\n\n #edi...,front page of marca 2019 05 08 edicola primap...,1

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,Score
39,Keep your mind wide open!\n#sevilla #academia ...,Wed,May,08,09,1,1,0,0,0,215,398,Sevilla English-Academia de Idiomas/Apoyo Escolar,"Sevilla, Andalucía, ESPAÑA",sevillaenglisha,keep your mind wide open!\n#sevilla #academia ...,keep your mind wide open sevilla academia ingl...,-1
143,"#ACMilan, #Leonardo intensifies #DiFrancesco c...",Wed,May,08,08,1,1,1,0,0,29389,2118,CalcioMercato (En),,CmdotCom_En,"#acmilan, #leonardo intensifies #difrancesco c...",acmilan leonardo intensifies difrancesco cont...,1
754,Feria de Abril is one of Seville's biggest eve...,Wed,May,08,07,0,1,1,0,0,1009,1834,Rayburn Education,Derby,RayburnEdu,feria de abril is one of seville's biggest eve...,feria de abril is one of seville s biggest eve...,0
988,Last day in #Sevilla . Went to the #FeriaSevil...,Wed,May,08,06,1,0,2,0,0,888,2854,Martina Collett,SW London,MartinaCollett,last day in #sevilla . went to the #feriasevil...,last day in sevilla went to the feriasevilla19...,1
1024,RT @lselvatico: Martes...\n.\n.\n.\n.\n@HdadSa...,Wed,May,08,06,1,0,0,0,2,1851,1482,Elias Beltran Fotografía ©,"Sevilla, España",ELIASBELTRANROD,rt @lselvatico: martes...\n.\n.\n.\n.\n@hdadsa...,rt lselvatico martes hdadsanesteban sevilla ma...,0
1069,Getting lost in the streets of #Sevilla now th...,Wed,May,08,06,1,1,1,0,0,5147,3061,Spain in Switzerland,"Zúrich, Suiza",Spain_in_CH,getting lost in the streets of #sevilla now th...,getting lost in the streets of sevilla now tha...,1
1158,"RT @BibinAlexander_: This day, that year! \n\n...",Wed,May,08,06,1,0,0,0,41,33744,15081,RK,India,Rajeesh077,"rt @bibinalexander_: this day, that year! \n\n...",rt bibinalexander_ this day that year seville ...,1
1238,This is not a Penguin Dancing Flamenco 💃🏿 by J...,Wed,May,08,05,1,1,0,0,0,69,52,Guit-ar by JuanPonte,"Irun, España",Guit_ar_,this is not a penguin dancing flamenco 💃🏿 by j...,this is not a penguin dancing flamenco by juan...,0
1282,"RT @I_Sobrini: Once the #IAIA19 is finished, i...",Wed,May,08,05,1,0,0,0,4,292,764,Juan C Tejeda Glez,,JuanCTejedaGlez,"rt @i_sobrini: once the #iaia19 is finished, i...",rt i_sobrini once the iaia19 is finished is ou...,1
1478,"ACCOUNT EXECUTIVE #empleo, #SEVILLA REF: 47555...",Wed,May,08,05,1,1,0,0,0,5558,25,Empleo Sevilla,Sevilla,EmpleoSevilla_,"account executive #empleo, #sevilla ref: 47555...",account executive empleo sevilla ref 4755538 h...,0
1838,"DEVOPS ENGINEER #empleo, #SEVILLA REF: 4754900...",Wed,May,08,04,1,1,0,0,0,5558,25,Empleo Sevilla,Sevilla,EmpleoSevilla_,"devops engineer #empleo, #sevilla ref: 4754900...",devops engineer empleo sevilla ref 4754900 htt...,0
1931,"RT @erlohr: Thrilled to have ""Noespera"" presel...",Wed,May,08,03,1,0,0,0,13,1922,1507,Angela,,AngelaKJones,"rt @erlohr: thrilled to have ""noespera"" presel...",rt erlohr thrilled to have noespera preselecte...,1
30,@The_RHS @CarolKlein As requested trying again...,Wed,May,08,10,1,0,0,1,0,439,566,Fiona Eldridge,London,coachfizz,@the_rhs @carolklein as requested trying again...,the_rhs carolklein as requested trying again ...,0
32,Explore the most beautiful places in Spain acc...,Wed,May,08,10,1,1,0,0,0,971,1006,Life On The Mediterranean,France,LifeOnTheMedSea,explore the most beautiful places in spain acc...,explore the most beautiful places in spain acc...,1
104,Private jets overflow the Seville airport for ...,Wed,May,08,10,0,1,0,0,0,253,800,TOACHINGS1.+ ©,"#Sevilla (#Spain, #España)",toachings,private jets overflow the seville airport for ...,private jets overflow the seville airport for ...,-1

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,Score
13,RT @ivanvaldezpy: Not today. \n#Liverpool #Bar...,Wed,May,08,09,1,0,0,0,2,11,77,Alexander Guerra,Italia,Alexguerra2378,rt @ivanvaldezpy: not today. \n#liverpool #bar...,rt ivanvaldezpy not today liverpool barcelona ...,0
32,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,09,0,0,0,0,8,1791,4896,B O L A J I ⚡️,Git Bash 🇳🇬,iambolajiayo,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
34,Find your #DreamHome in #Valencia #AreaGuide #...,Wed,May,08,09,1,1,0,0,0,1347,1392,Property Guides,"London, England",Property_Guides,find your #dreamhome in #valencia #areaguide #...,find your dreamhome in valencia areaguide insp...,0
41,Good morning from #València! Let's start the d...,Wed,May,08,09,1,0,0,0,0,2885,1665,Valencia Tourism,Valencia (Spain),ValenciaCity,good morning from #valència! let's start the d...,good morning from valència let s start the day...,1
50,RT @TonyBet: Here we go: #Barca fans have call...,Wed,May,08,08,1,0,0,0,1,6,54,Muhammad waseem,"Lahore, Pakistan",Muhamma57283859,rt @tonybet: here we go: #barca fans have call...,rt tonybet here we go barca fans have called f...,1
52,RT @TheOG_Gaganoid: Somebody should please che...,Wed,May,08,08,1,0,0,0,1,1030,746,Si Señor,"Lagos, Nigeria",ManLikeWaji,rt @theog_gaganoid: somebody should please che...,rt theog_gaganoid somebody should please check...,0
54,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,08,0,0,0,0,8,970,7,WebCamp,Barcelona,webcamp,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
55,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,08,0,0,0,0,8,38,38,IonicSpain,Barcelona,ionicspain,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
57,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,08,0,0,0,0,8,5673,2869,hackcolab,"C/Sant Pere Més Alt 27, Barcelona",hackcolab,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
58,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,08,0,0,0,0,8,794,2041,CinemaJS,"Barcelona, Catalunya",CinemaJS,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
59,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,08,0,0,0,0,8,634,386,AngularCamp,Barcelona,angularcamp,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
60,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,08,0,0,0,0,8,229,177,AngularBeers,Barcelona,AngularBeers,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
63,RT @jscamp: Our mission is not to be the bigge...,Wed,May,08,08,0,0,0,0,8,5622,2629,David Pich,"Barcelona, Catalonia",davidpich,rt @jscamp: our mission is not to be the bigge...,rt jscamp our mission is not to be the biggest...,1
73,Our mission is not to be the biggest conferenc...,Wed,May,08,08,0,1,2,0,8,5005,614,JSCamp,Barcelona,jscamp,our mission is not to be the biggest conferenc...,our mission is not to be the biggest conferenc...,1
77,Well done #LIVERPOOL u deserved this victory a...,Wed,May,08,08,1,0,1,0,0,129,210,Jass gill,Spain,JassSinghGill1,well done #liverpool u deserved this victory a...,well done liverpool u deserved this victory an...,1

In [328]:
pos_tweets = sum(df_rm['Score']>0)

In [330]:
print("the number of positive tweets for real madrid: ", pos_tweets)

the number of positive tweets for real madrid:  63

In [331]:
neu_tweets = sum(df_rm['Score']==0)

In [332]:
print("the number of neutral tweets for real madrid: ", neu_tweets)

the number of neutral tweets for real madrid:  57

In [333]:
neg_tweets = sum(df_rm['Score']<0)

In [334]:
print("the number of negative tweets for real madrid: ", neg_tweets)

the number of negative tweets for real madrid:  12

In [335]:
pos_tweets_b = sum(df_barca['Score']>0)
neu_tweets_b = sum(df_barca['Score']==0)
neg_tweets_b = sum(df_barca['Score']<0)

In [336]:
print("the number of positive tweets for barcelona: ", pos_tweets_b)

the number of positive tweets for barcelona:  1219

In [337]:
print("the number of neutral tweets for barcelona: ", neu_tweets_b)

the number of neutral tweets for barcelona:  1502

In [340]:
print("the number of negative tweets for barcelona: ", neg_tweets_b)

the number of negative tweets for barcelona:  317

In [339]:
pos_tweets_atm = sum(df_atm['Score']>0)
neu_tweets_atm = sum(df_atm['Score']==0)
neg_tweets_atm = sum(df_atm['Score']<0)

In [341]:
print("the number of postive tweets for atletico: ", pos_tweets_atm)

the number of postive tweets for atletico:  22

In [342]:
print("the number of negative tweets for atletico: ", neg_tweets_atm)

the number of negative tweets for atletico:  0

In [343]:
print("the number of neutral tweets for atletico: ", neu_tweets_atm)

the number of neutral tweets for atletico:  11

In [383]:
pos_tweets_sev = sum(df_sev['Score']>0)
neu_tweets_sev = sum(df_sev['Score']==0)
neg_tweets_sev = sum(df_sev['Score']<0)

In [384]:
print("the number of postive tweets for sevilla: ", pos_tweets_sev)

the number of postive tweets for sevilla:  13

In [385]:
print("the number of neutral tweets for sevilla: ", neu_tweets_sev)

the number of neutral tweets for sevilla:  13

In [386]:
print("the number of negative tweets for sevilla: ", neg_tweets_sev)

the number of negative tweets for sevilla:  3

In [387]:
pos_tweets_val = sum(df_val['Score']>0)
neu_tweets_val = sum(df_val['Score']==0)
neg_tweets_val = sum(df_val['Score']<0)

In [388]:
print("the number of postive tweets for valencia: ", pos_tweets_val)

the number of postive tweets for valencia:  81

In [389]:
print("the number of negative tweets for valencia: ", neg_tweets_val)

the number of negative tweets for valencia:  24

In [390]:
print("the number of neutral tweets for valencia: ", neu_tweets_val)

the number of neutral tweets for valencia:  111

In [366]:
print('Percentage of Positive tweets for real madrid: ',((pos_tweets)/len(df_rm)*100))

Percentage of Positive tweets for real madrid:  47.72727272727273

In [367]:
print('Percentage of Neutral tweets for real madrid: ',((neu_tweets)/len(df_rm)*100))

Percentage of Neutral tweets for real madrid:  43.18181818181818

In [368]:
print('Percentage of Negative tweets for real madrid: ',((neg_tweets)/len(df_rm)*100))

Percentage of Negative tweets for real madrid:  9.090909090909092

In [369]:
print('Percentage of Positive tweets for barcelona: ',((pos_tweets_b)/len(df_barca)*100))

Percentage of Positive tweets for barcelona:  40.125082290980906

In [372]:
print('Percentage of Neutral tweets for barcelona: ',((neu_tweets_b)/len(df_barca)*100))

Percentage of Neutral tweets for barcelona:  49.44042132982226

In [374]:
print('Percentage of Negative tweets for barcelona: ',((neg_tweets_b)/len(df_barca)*100))

Percentage of Negative tweets for barcelona:  10.43449637919684

In [376]:
print('Percentage of Positive tweets for atletico: ',((pos_tweets_atm)/len(df_atm)*100))

Percentage of Positive tweets for atletico:  66.66666666666666

In [377]:
print('Percentage of Neutral tweets for atletico: ',((neu_tweets_atm)/len(df_atm)*100))

Percentage of Neutral tweets for atletico:  33.33333333333333

In [378]:
print('Percentage of Negative tweets for atletico: ',((neg_tweets_atm)/len(df_atm)*100))

Percentage of Negative tweets for atletico:  0.0

In [379]:
print('Percentage of Positive tweets for Sevilla: ',((pos_tweets_sev)/len(df_sev)*100))

Percentage of Positive tweets for Sevilla:  44.827586206896555

In [392]:
print('Percentage of Neutral tweets for Sevilla: ',((neu_tweets_sev)/len(df_sev)*100))

Percentage of Neutral tweets for Sevilla:  44.827586206896555

In [393]:
print('Percentage of Negative tweets for Sevilla: ',((neg_tweets_sev)/len(df_sev)*100))

Percentage of Negative tweets for Sevilla:  10.344827586206897

In [394]:
print('Percentage of Positive tweets for Valencia: ',((pos_tweets_val)/len(df_val)*100))

Percentage of Positive tweets for Valencia:  37.5

In [395]:
print('Percentage of Neutral tweets for Valencia: ',((neu_tweets_val)/len(df_val)*100))

Percentage of Neutral tweets for Valencia:  51.388888888888886

In [411]:
print('Percentage of Negative tweets for Valencia: ',((neg_tweets_val)/len(df_val)*100))

Percentage of Negative tweets for Valencia:  11.11111111111111

In [ ]:
df.head(2)

In [403]:
from nltk.corpus import stopwords  
from sklearn.feature_extraction.text import CountVectorizer
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to C:\Users\Prashant
[nltk_data]     Chaudhary\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.

True

In [439]:
vectorizer = CountVectorizer(max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))

In [441]:
df['F'] = df['E']

In [442]:
df.head()

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,F,Score,Sentiment
0,Good morning #Barcelona...Good advice for #Bar...,Wed,May,08,09,1,1,0,0,0,1691,3473,Pedro de la Vega,Barcelona,BcnFox,good morning #barcelona...good advice for #bar...,good morning barcelona good advice for barça f...,good morning barcelona good advice for barça f...,1,Positive
1,RT @YusufChambers: #MoSalah gets injured.\n#ra...,Wed,May,08,09,1,0,0,0,4,37,233,Yaseen,"Johannesburg, South Africa",yaseenyazo,rt @yusufchambers: #mosalah gets injured.\n#ra...,rt yusufchambers mosalah gets injured ramadhan...,rt yusufchambers mosalah gets injured ramadhan...,0,Neutral
2,👉 @FinalScoresBET #fsb #winfornow this is the ...,Wed,May,08,09,1,1,0,0,0,47,30,FSB win-for-now,"Abuja, Nigeria",fsbODDtips,👉 @finalscoresbet #fsb #winfornow this is the ...,finalscoresbet fsb winfornow this is the most...,finalscoresbet fsb winfornow this is the most...,1,Positive
3,RT @LFCphoto: No problem. #LFC #LIVBAR #Champi...,Wed,May,08,09,1,0,0,0,21,38,317,🍀OOR🍀THEKOP🍀핫티스🍀판타지🍀,태국.Thailand,ameerah_TY,rt @lfcphoto: no problem. #lfc #livbar #champi...,rt lfcphoto no problem lfc livbar championslea...,rt lfcphoto no problem lfc livbar championslea...,0,Neutral
4,RT @MARCABIMBO: WE CHOOSE TO BELIEVE IN US @ma...,Wed,May,08,09,1,0,0,0,12,141,874,Linda Guy,,yessylamb84,rt @marcabimbo: we choose to believe in us @ma...,rt marcabimbo we choose to believe in us mazai...,rt marcabimbo we choose to believe in us mazai...,0,Neutral

In [443]:
df['F'] = vectorizer.fit_transform(df['F']).toarray()

In [445]:
df.head()

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,F,Score,Sentiment
0,Good morning #Barcelona...Good advice for #Bar...,Wed,May,08,09,1,1,0,0,0,1691,3473,Pedro de la Vega,Barcelona,BcnFox,good morning #barcelona...good advice for #bar...,good morning barcelona good advice for barça f...,0,1,Positive
1,RT @YusufChambers: #MoSalah gets injured.\n#ra...,Wed,May,08,09,1,0,0,0,4,37,233,Yaseen,"Johannesburg, South Africa",yaseenyazo,rt @yusufchambers: #mosalah gets injured.\n#ra...,rt yusufchambers mosalah gets injured ramadhan...,0,0,Neutral
2,👉 @FinalScoresBET #fsb #winfornow this is the ...,Wed,May,08,09,1,1,0,0,0,47,30,FSB win-for-now,"Abuja, Nigeria",fsbODDtips,👉 @finalscoresbet #fsb #winfornow this is the ...,finalscoresbet fsb winfornow this is the most...,0,1,Positive
3,RT @LFCphoto: No problem. #LFC #LIVBAR #Champi...,Wed,May,08,09,1,0,0,0,21,38,317,🍀OOR🍀THEKOP🍀핫티스🍀판타지🍀,태국.Thailand,ameerah_TY,rt @lfcphoto: no problem. #lfc #livbar #champi...,rt lfcphoto no problem lfc livbar championslea...,0,0,Neutral
4,RT @MARCABIMBO: WE CHOOSE TO BELIEVE IN US @ma...,Wed,May,08,09,1,0,0,0,12,141,874,Linda Guy,,yessylamb84,rt @marcabimbo: we choose to believe in us @ma...,rt marcabimbo we choose to believe in us mazai...,0,0,Neutral

In [446]:
X_train, X_test, y_train, y_test = train_test_split(df['F'], df['Sentiment'], test_size=0.2, random_state=0)

In [510]:
from sklearn.ensemble import RandomForestClassifier

text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)  
text_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [448]:
df.head(2)

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,followers,following,user,location,screen_name,lower case,E,F,Score,Sentiment
0,Good morning #Barcelona...Good advice for #Bar...,Wed,May,08,09,1,1,0,0,0,1691,3473,Pedro de la Vega,Barcelona,BcnFox,good morning #barcelona...good advice for #bar...,good morning barcelona good advice for barça f...,0,1,Positive
1,RT @YusufChambers: #MoSalah gets injured.\n#ra...,Wed,May,08,09,1,0,0,0,4,37,233,Yaseen,"Johannesburg, South Africa",yaseenyazo,rt @yusufchambers: #mosalah gets injured.\n#ra...,rt yusufchambers mosalah gets injured ramadhan...,0,0,Neutral

In [434]:
df['Score'] = np.array([ analize_sentiment(tweet) for tweet in df['E'] ])

In [436]:
df['Sentiment'] = ["Positive" if x ==1 else "Neutral" if x ==0 else "Negative" for x in df['Score']]

In [449]:
features = df.iloc[:, 16].values  
labels = df.iloc[:, 19].values

In [453]:
from nltk.corpus import stopwords  
from sklearn.feature_extraction.text import CountVectorizer

vectorizer = CountVectorizer(max_features=2500, min_df=7, max_df=0.8, stop_words=stopwords.words('english'))  
features = vectorizer.fit_transform(features).toarray()

In [454]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(features, labels, test_size=0.2, random_state=0)

In [455]:
from sklearn.ensemble import RandomForestClassifier

text_classifier = RandomForestClassifier(n_estimators=200, random_state=0)  
text_classifier.fit(X_train, y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
            max_depth=None, max_features='auto', max_leaf_nodes=None,
            min_impurity_decrease=0.0, min_impurity_split=None,
            min_samples_leaf=1, min_samples_split=2,
            min_weight_fraction_leaf=0.0, n_estimators=200, n_jobs=None,
            oob_score=False, random_state=0, verbose=0, warm_start=False)

In [456]:
predictions = text_classifier.predict(X_test)

In [465]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score 

print(confusion_matrix(y_test,predictions))  
print(classification_report(y_test,predictions))  
print('Accuracy of the model: ',accuracy_score(y_test, predictions))

[[ 79   5   6]
 [  2 379   4]
 [  1  20 316]]
              precision    recall  f1-score   support

    Negative       0.96      0.88      0.92        90
     Neutral       0.94      0.98      0.96       385
    Positive       0.97      0.94      0.95       337

   micro avg       0.95      0.95      0.95       812
   macro avg       0.96      0.93      0.94       812
weighted avg       0.95      0.95      0.95       812

Accuracy of the model:  0.9532019704433498

In [493]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [494]:
df['G'] = df['E']

In [495]:
df.head()

,text,weekday,month,day,hour,has_hashtag,has_url,fav_count,is_reply,retweet_count,...,following,user,location,screen_name,lower case,E,F,Score,Sentiment,G
0,Good morning #Barcelona...Good advice for #Bar...,Wed,May,08,09,1,1,0,0,0,...,3473,Pedro de la Vega,Barcelona,BcnFox,good morning #barcelona...good advice for #bar...,good morning barcelona good advice for barça f...,0,1,Positive,good morning barcelona good advice for barça f...
1,RT @YusufChambers: #MoSalah gets injured.\n#ra...,Wed,May,08,09,1,0,0,0,4,...,233,Yaseen,"Johannesburg, South Africa",yaseenyazo,rt @yusufchambers: #mosalah gets injured.\n#ra...,rt yusufchambers mosalah gets injured ramadhan...,0,0,Neutral,rt yusufchambers mosalah gets injured ramadhan...
2,👉 @FinalScoresBET #fsb #winfornow this is the ...,Wed,May,08,09,1,1,0,0,0,...,30,FSB win-for-now,"Abuja, Nigeria",fsbODDtips,👉 @finalscoresbet #fsb #winfornow this is the ...,finalscoresbet fsb winfornow this is the most...,0,1,Positive,finalscoresbet fsb winfornow this is the most...
3,RT @LFCphoto: No problem. #LFC #LIVBAR #Champi...,Wed,May,08,09,1,0,0,0,21,...,317,🍀OOR🍀THEKOP🍀핫티스🍀판타지🍀,태국.Thailand,ameerah_TY,rt @lfcphoto: no problem. #lfc #livbar #champi...,rt lfcphoto no problem lfc livbar championslea...,0,0,Neutral,rt lfcphoto no problem lfc livbar championslea...
4,RT @MARCABIMBO: WE CHOOSE TO BELIEVE IN US @ma...,Wed,May,08,09,1,0,0,0,12,...,874,Linda Guy,,yessylamb84,rt @marcabimbo: we choose to believe in us @ma...,rt marcabimbo we choose to believe in us mazai...,0,0,Neutral,rt marcabimbo we choose to believe in us mazai...

In [496]:
from sklearn.feature_extraction.text import CountVectorizer

cv = CountVectorizer(binary=True)
cv.fit(df['G'])
X = cv.transform(df['G'])

In [497]:
X_test = cv.transform(df['G'])

In [501]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split

In [502]:
labels = df.iloc[:, 19].values

In [508]:
X_train, X_val, y_train, y_val = train_test_split(
    X, labels, train_size = 0.80
)

for c in [0.01, 0.05, 0.25, 0.5]:
    
    lr = LogisticRegression(C=c)
    lr.fit(X_train, y_train)
    print ("Accuracy for C=%s: %s" 
           % (c, accuracy_score(y_val, lr.predict(X_val))))

Accuracy for C=0.01: 0.7512315270935961
Accuracy for C=0.05: 0.8448275862068966
Accuracy for C=0.25: 0.9285714285714286
Accuracy for C=0.5: 0.9482758620689655

In [509]:
final_model = LogisticRegression(C=0.5)
final_model.fit(X, labels)
print ("Final Accuracy: %s" 
       % accuracy_score(labels, final_model.predict(X_test)))

Final Accuracy: 0.9955654101995566